// End-to-end replay: MCAP bag -> SonarCfarFrontend -> FactorBuilders ->
// PoseGraphProblem -> GaussNewtonSolver -> StateStore -> SubmapManager ->
// trajectory + ATE + RunManifest. This is the concrete proof that the
// layers described in the architecture design actually compose, run on
// synthetic data generated by apps/synth_bag_gen.cpp (this machine has
// neither HoloOcean nor ROS2).
//
// v1 limitations, documented rather than hidden:
//  - No real reliability scheduler / learned-model information cap (section
//    8.4): sqrt-information values below are fixed constants, not a
//    calibrated reliability policy.
//  - Landmark association for the sonar range factor now goes through a
//    real SubmapManager::QueryNearestPoint() call (see the sonar block
//    below): a detection within kLandmarkGateM of an already-known
//    landmark reuses that landmark's stored position; a miss inserts a
//    brand new one. What's still v1 (per sonar_range_factor's documented
//    limitation): sonar range+bearing alone can't observe elevation, so a
//    newly-inserted landmark's z is a placeholder (level with the sensor)
//    that nothing later refines — no joint landmark estimation yet, and no
//    covariance-aware (Mahalanobis) gating, just a fixed Euclidean radius.
//  - Sonar: only the top-ranked DBSCAN cluster per SonarFrame is consumed
//    (schemas/proto/uw/domain/hypothesis.proto's documented v1 rule — the
//    wire contract keeps room for a multi-hypothesis consumer, this app
//    isn't one). synth_bag_gen emits one synthetic ping per target-in-range
//    rather than one ping covering all of them, so this doesn't lose
//    information in THIS demo's scenario, but it isn't a general multi-
//    target-per-ping model — see synth_bag_gen's own header for that
//    caveat.
//  - Layered config (defaults/rig/scenario/experiment, section 14.2) covers
//    solver options and factor sqrt-information constants via --experiment
//    (see uw::runtime::LoadExperimentConfig). estimator_mode and
//    landmark_detector genuinely dispatch (see the stereo_landmark_vo
//    block below); sonar_frontend/optical_frontend/map_backend still only
//    ever run one hardcoded implementation each (sonar_range_v1 +
//    depth_v1 + submap_point_cloud_v1) because no second implementation
//    exists yet — but as of ValidateExperimentConfigSelections(), naming
//    anything else in an experiment YAML fails the run at startup instead
//    of silently running that one pipeline anyway.
//  - defaults.warmup_seconds (0 by default) keeps keyframes inside the
//    warmup window in the graph and dead-reckoned via relative-pose
//    factors, but withholds sonar-range/depth ("absolute reference")
//    factors for them until the window ends. kf0 stays the fixed anchor
//    regardless. See the warmup block below for why.
#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <ctime>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <optional>
#include <set>
#include <sstream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include <sys/utsname.h>

#include "application/event_pump.hpp"
#include "application/replay_input_accumulator.hpp"
#include "application/replay_pipeline.hpp"
#include "domain/domain.hpp"
#include "estimation/gauss_newton_solver.hpp"
#include "estimation/pose_graph_problem.hpp"
#include "estimation/state_store.hpp"
#include "evaluation/trajectory_metrics.hpp"
#include "factor_builders/depth_factor_builder.hpp"
#include "factor_builders/imu_preintegration_factor_builder.hpp"
#include "factor_builders/inertial_prior_residual.hpp"
#include "factor_builders/relative_pose_factor_builder.hpp"
#include "factor_builders/sonar_range_factor_builder.hpp"
#include "frontends/acoustic_optic_depth_fusion_frontend.hpp"
#include "frontends/imu_preintegration_frontend.hpp"
#include "frontends/imu_stationary_initializer.hpp"
#include "frontends/loop_closure_frontend.hpp"
#include "frontends/sonar_cfar_frontend.hpp"
#include "frontends/stereo_landmark_vo_frontend.hpp"
#include "frontends/stereo_optical_depth_frontend.hpp"
#include "mapping/acoustic_optic_map_bridge.hpp"
#include "mapping/submap_manager.hpp"
#include "opencv_adapters/stereo_rectifier.hpp"
#include "runtime/acoustic_optic_synchronizer.hpp"
#include "runtime/canonical_topics.hpp"
#include "runtime/config.hpp"
#include "runtime/mcap_event_source.hpp"
#include "runtime/run_manifest.hpp"
#include "sensor_models/geometry.hpp"
#include "sensor_models/imu_preintegration.hpp"
#include "sensor_models/sonar_beam_model.hpp"

using uw::sensor_models::Pose3;

namespace {

std::string ToTumLine(double timestamp_s, const Pose3& pose) {
  std::ostringstream out;
  out.precision(9);
  out << timestamp_s << " " << pose.translation.x() << " " << pose.translation.y() << " "
      << pose.translation.z() << " " << pose.rotation.x() << " " << pose.rotation.y() << " "
      << pose.rotation.z() << " " << pose.rotation.w();
  return out.str();
}

// RunManifest population helpers (docs/archive/uw-slam-production-readiness-and-
// roadmap-2026-08-21.md section 5.6: these fields were all silently empty
// before). Kept deliberately simple — no new dependency pulled in just to
// fill provenance metadata.

std::string NowIso8601Utc() {
  const auto now = std::chrono::system_clock::now();
  const std::time_t now_c = std::chrono::system_clock::to_time_t(now);
  std::tm utc_tm{};
  gmtime_r(&now_c, &utc_tm);
  std::ostringstream out;
  out << std::put_time(&utc_tm, "%Y-%m-%dT%H:%M:%SZ");
  return out.str();
}

// Not a cryptographic hash — just enough to detect "this config/calibration
// file's bytes changed since a prior run" for manifest provenance, not to
// resist tampering.
std::string Fnv1aHex(const std::string& data) {
  uint64_t hash = 1469598103934665603ull;  // FNV offset basis
  for (unsigned char c : data) {
    hash ^= c;
    hash *= 1099511628211ull;  // FNV prime
  }
  std::ostringstream out;
  out << std::hex << hash;
  return out.str();
}

std::string ReadFileBytesOrEmpty(const std::string& path) {
  std::ifstream in(path, std::ios::binary);
  if (!in) return "";
  std::ostringstream buffer;
  buffer << in.rdbuf();
  return buffer.str();
}

std::string DetectOsInfo() {
  struct utsname info{};
  if (uname(&info) != 0) return "unknown";
  return std::string(info.sysname) + " " + info.release + " " + info.machine;
}

// Linux-specific (this codebase's dev/CI environment per CLAUDE.md); a
// non-Linux build just gets "unknown" rather than failing to compile.
std::string DetectCpuInfo() {
  std::ifstream cpuinfo("/proc/cpuinfo");
  std::string line;
  while (std::getline(cpuinfo, line)) {
    const auto colon = line.find(':');
    if (colon != std::string::npos && line.compare(0, 10, "model name") == 0) {
      std::string value = line.substr(colon + 1);
      const auto first = value.find_first_not_of(' ');
      return first == std::string::npos ? "unknown" : value.substr(first);
    }
  }
  return "unknown";
}

}  // namespace

uw::domain::StateSnapshot::TrackingStatus uw::application::DecideTrackingStatus(
    const ReplayTrackingInputs& inputs) {
  if (inputs.vo_enabled && inputs.vo_health == uw::domain::HealthReport::STATUS_UNAVAILABLE) {
    return uw::domain::StateSnapshot::TRACKING_STATUS_LOST;
  }
  if (!inputs.solver_converged ||
      (inputs.vo_enabled && inputs.vo_health == uw::domain::HealthReport::STATUS_SUSPECT)) {
    return uw::domain::StateSnapshot::TRACKING_STATUS_DEGRADED;
  }
  return uw::domain::StateSnapshot::TRACKING_STATUS_TRACKING;
}

uw::domain::StateSnapshot uw::application::BuildStateSnapshot(const StateSnapshotInputs& inputs) {
  uw::domain::StateSnapshot snapshot;
  snapshot.mutable_state_id()->set_value(inputs.state_id);
  snapshot.mutable_state_version()->set_value(inputs.state_version);
  *snapshot.mutable_capture_timestamp() = inputs.capture_timestamp;
  *snapshot.mutable_pose_wb() = inputs.pose.ToProto();
  snapshot.set_tracking_status(inputs.tracking_status);
  snapshot.mutable_calibration_version()->set_value(inputs.calibration_version);

  std::vector<std::string> evidence_values;
  evidence_values.reserve(inputs.contributing_evidence.size());
  for (const auto& id : inputs.contributing_evidence) evidence_values.push_back(id.value());
  std::sort(evidence_values.begin(), evidence_values.end());
  evidence_values.erase(std::unique(evidence_values.begin(), evidence_values.end()),
                        evidence_values.end());
  for (const auto& value : evidence_values) snapshot.add_contributing_measurements()->set_value(value);
  return snapshot;
}

uw::application::MapContributionCounts uw::application::CountDepthContributions(
    const uw::domain::FusedDepthMeasurement& fused) {
  MapContributionCounts counts;
  for (unsigned char byte : fused.contribution_mask()) {
    if (byte == static_cast<unsigned char>(uw::domain::DEPTH_CONTRIBUTION_OPTICAL_ONLY)) {
      ++counts.optical_only_points;
    } else if (byte == static_cast<unsigned char>(uw::domain::DEPTH_CONTRIBUTION_ACOUSTIC_OPTIC)) {
      ++counts.acoustic_optic_points;
    }
  }
  return counts;
}

std::string uw::application::FormatReplayRunSummary(
    const uw::application::ReplayRunSummary& summary) {
  std::ostringstream out;
  auto emit = [&out](const char* key, const std::string& value) {
    out << "summary." << key << "=" << value << "\n";
  };
  auto emit_int = [&](const char* key, long long value) { emit(key, std::to_string(value)); };
  auto emit_double = [&](const char* key, double value) {
    char buffer[64];
    std::snprintf(buffer, sizeof(buffer), "%.9f", value);
    emit(key, buffer);
  };

  emit("estimator_mode", summary.estimator_mode);
  emit("solver", summary.solver);
  emit("solver_converged", summary.solver_converged ? "true" : "false");
  emit_int("solver_iterations", summary.solver_iterations);
  emit_double("initial_cost", summary.initial_cost);
  emit_double("final_cost", summary.final_cost);
  emit_int("keyframe_count", summary.keyframe_count);
  emit_int("keyframe_boundary_count", summary.keyframe_boundary_count);
  emit_int("imu_factor_count", summary.imu_factor_count);
  emit_int("imu_interval_rejected_count", summary.imu_interval_rejected_count);
  emit_int("relative_pose_factor_count", summary.relative_pose_factor_count);
  emit_int("loop_closure_factor_count", summary.loop_closure_factor_count);
  emit_int("sonar_range_factor_count", summary.sonar_range_factor_count);
  emit_int("depth_factor_count", summary.depth_factor_count);
  emit_int("landmark_count", summary.landmark_count);
  emit("initialization", summary.initialization);
  emit_int("free_parameter_dim", summary.free_parameter_dim);
  emit_int("residual_dim", summary.residual_dim);
  emit_double("ate_rmse_m", summary.ate_rmse_m);
  emit_int("ate_matched_poses", summary.ate_matched_poses);
  return out.str();
}

uw::application::GraphObservability uw::application::CheckGraphObservability(
    uw::estimation::PoseGraphProblem& problem) {
  uw::application::GraphObservability result;

  // Key on (kind, id): a keyframe's pose block and its inertial block are
  // separate parameters, separately constrained. Conflating them would hide
  // exactly the failure this exists to catch -- an inertial state with no
  // IMU edge and no prior sitting next to a well-constrained pose of the
  // same name.
  std::set<std::pair<int, std::string>> free_blocks;
  for (const auto& block : problem.MutableAllParameterBlocks()) {
    if (block.fixed) continue;
    free_blocks.insert({static_cast<int>(block.ref.kind), block.ref.keyframe_id});
  }

  std::set<std::pair<int, std::string>> referenced;
  for (const auto& binding : problem.ResidualBindings()) {
    if (binding.involved_parameters == nullptr) continue;
    bool touches_a_free_block = false;
    for (const auto& ref : *binding.involved_parameters) {
      const std::pair<int, std::string> key{static_cast<int>(ref.kind), ref.keyframe_id};
      referenced.insert(key);
      if (free_blocks.count(key) > 0) touches_a_free_block = true;
    }
    // A residual wired only to fixed blocks (the anchor's own depth factor,
    // say) is a constant: it contributes no information about anything the
    // solver moves, so counting its rows would inflate the tally and mask a
    // genuine rank deficiency elsewhere.
    if (touches_a_free_block) result.residual_dim += binding.block->ResidualDim();
  }

  for (const auto& block : problem.MutableAllParameterBlocks()) {
    if (block.fixed) continue;  // fixed blocks are not solved for
    // MINIMAL dimension, not block size: a pose is stored as 7 numbers but
    // has 6 degrees of freedom (the quaternion is normalized, and the
    // residual is invariant along it -- see imu_preintegration_residual.hpp
    // on why that column is genuinely zero). Counting 7 would declare a
    // perfectly determined relative-pose chain -- 6 rows per edge against
    // 7 "columns" per keyframe -- structurally singular and hard-fail every
    // experiment that has no depth or sonar factors to make up the
    // difference.
    result.free_parameter_dim +=
        block.ref.kind == uw::estimation::PoseGraphProblem::ParameterKind::kPose ? 6 : block.size;
    if (referenced.count({static_cast<int>(block.ref.kind), block.ref.keyframe_id}) == 0) {
      result.problems.push_back(
          std::string(block.ref.kind == uw::estimation::PoseGraphProblem::ParameterKind::kInertial
                          ? "inertial state '"
                          : "keyframe pose '") +
          block.ref.keyframe_id + "' is free but referenced by no residual — the normal equations "
          "are singular in those " + std::to_string(block.size) + " columns");
    }
  }

  if (result.residual_dim < result.free_parameter_dim) {
    result.problems.push_back("the graph has " + std::to_string(result.residual_dim) +
                              " residual rows for " + std::to_string(result.free_parameter_dim) +
                              " free parameters — underdetermined, and LM damping would return an "
                              "arbitrary answer rather than fail");
  }
  return result;
}

std::vector<std::string> uw::application::EvaluateReplayGates(
    const uw::runtime::PlatformDefaultsConfig& defaults, const uw::estimation::GaussNewtonSummary& solver,
    const uw::evaluation::AteResult& ate, int num_landmarks, const MapContributionCounts& contributions,
    int num_acoustic_optic_accepted) {
  std::vector<std::string> failures;
  if (defaults.require_converged && !solver.converged) {
    failures.push_back("solver did not converge (" + std::to_string(solver.iterations) +
                       " iterations, stalled)");
  }
  if (defaults.min_matched_ate_poses > 0 &&
      static_cast<int>(ate.num_matched_poses) < defaults.min_matched_ate_poses) {
    failures.push_back("matched ATE poses " + std::to_string(ate.num_matched_poses) + " < required " +
                       std::to_string(defaults.min_matched_ate_poses));
  }
  if (defaults.max_ate_rmse_m >= 0.0 && ate.rmse_m > defaults.max_ate_rmse_m) {
    failures.push_back("ATE rmse " + std::to_string(ate.rmse_m) + "m > max " +
                       std::to_string(defaults.max_ate_rmse_m) + "m");
  }
  const uint64_t total_map_points = contributions.optical_only_points + contributions.acoustic_optic_points;
  if (defaults.require_nonempty_map && (static_cast<uint64_t>(num_landmarks) + total_map_points) == 0) {
    failures.push_back("map is empty (0 landmarks discovered, 0 map evidence points)");
  }
  if (defaults.min_acoustic_optic_accepted > 0 &&
      num_acoustic_optic_accepted < defaults.min_acoustic_optic_accepted) {
    failures.push_back("acoustic-optic accepted associations " +
                       std::to_string(num_acoustic_optic_accepted) + " < required " +
                       std::to_string(defaults.min_acoustic_optic_accepted));
  }
  if (defaults.min_acoustic_optic_map_points > 0 &&
      contributions.acoustic_optic_points < static_cast<uint64_t>(defaults.min_acoustic_optic_map_points)) {
    failures.push_back("acoustic-optic map points " + std::to_string(contributions.acoustic_optic_points) +
                       " < required " + std::to_string(defaults.min_acoustic_optic_map_points));
  }
  return failures;
}

uw::frontends::SonarCfarFrontendParams uw::application::BuildSonarCfarFrontendParams(
    const uw::runtime::SonarFrontendConfig& config) {
  uw::frontends::SonarCfarFrontendParams params;
  params.cfar.num_training_cells = config.training_cells;
  params.cfar.num_guard_cells = config.guard_cells;
  params.cfar.probability_false_alarm = config.probability_false_alarm;
  params.detector_threshold = static_cast<uint8_t>(config.detector_threshold);
  params.dbscan_eps_m = config.dbscan_eps_m;
  params.dbscan_min_samples = config.dbscan_min_samples;
  params.default_range_sigma_m = config.default_range_sigma_m;
  params.default_bearing_sigma_rad = config.default_bearing_sigma_rad;
  return params;
}

int uw::application::RunReplayPipeline(const ReplayOptions& opt,
                                       const std::string& git_commit) {
  if (opt.bag_path.empty()) {
    std::cerr << "replay pipeline requires a bag path\n";
    return 1;
  }
  const std::string run_start_time_iso8601 = NowIso8601Utc();
  // Layer 1: platform defaults (either from --experiment's defaults: layer,
  // or this struct's built-in values — same numbers previously hardcoded
  // as kRelativePoseSqrtInfo etc. below, now factored out to
  // uw::runtime::PlatformDefaultsConfig so they have exactly one
  // definition, in configs/defaults/platform.yaml).
  uw::runtime::PlatformDefaultsConfig defaults;
  bool write_run_manifest = true;
  // Only set when --experiment loads a rig with cameras — gates the new
  // acoustic-optic pass below so the no-experiment path (used by
  // tests/l2_replay/determinism_test.sh) is provably unchanged.
  std::optional<uw::domain::RigCalibrationSnapshot> rig;
  // Was read-but-unused before stereo_landmark_vo_frontend (see README's
  // "已知边界" — experiment's frontend/estimator/map-backend selection
  // fields didn't actually dispatch on anything). "stereo_landmark_vo"
  // is the first value that does: it switches the relative-pose block
  // below from synth_bag_gen's ground-truth+noise "black-box VIO" bag
  // evidence to real evidence computed from /raw/camera/left,right — see
  // that block for why this needs `rig` too, not just this string.
  std::string estimator_mode = "black_box_vio";
  // Set instead when estimator_mode is "imu_preintegration". Kept separate
  // from `rig` above because that one is deliberately only populated for a
  // rig WITH cameras (it gates the acoustic-optic pass), while the inertial
  // path needs the imu_noise block and the base_link->imu_link edge of a
  // camera-less rig such as configs/rig/example_auv_sonar_only.yaml.
  std::optional<uw::domain::RigCalibrationSnapshot> imu_rig;
  std::string landmark_detector = "bright_blob";
  // RunManifest provenance (section 5.6): best-effort, not a guarantee — the
  // seed reflects this experiment's declared scenario seed, which is what
  // would generate a matching bag via synth_bag_gen, but a bag supplied from
  // elsewhere (e.g. a real HoloOcean recording) may not have come from it.
  uint64_t scenario_seed = 0;
  std::string config_hash;
  std::string calibration_hash;
  if (!opt.experiment_path.empty()) {
    const auto config = uw::runtime::LoadExperimentConfig(opt.experiment_path);
    if (const auto error = uw::runtime::ValidateExperimentConfigSelections(config)) {
      std::cerr << "invalid experiment config " << opt.experiment_path << ": " << *error << "\n";
      return 1;
    }
    defaults = config.defaults;
    write_run_manifest = config.write_run_manifest;
    if (config.rig.cameras_size() > 0) rig = config.rig;
    estimator_mode = config.estimator_mode;
    if (config.estimator_mode == "imu_preintegration") imu_rig = config.rig;
    landmark_detector = config.landmark_detector;
    scenario_seed = config.scenario.seed;
    config_hash = Fnv1aHex(ReadFileBytesOrEmpty(opt.experiment_path));
    calibration_hash = Fnv1aHex(config.rig.SerializeAsString());
    std::cout << "loaded experiment config: " << opt.experiment_path << " (sonar_frontend="
              << config.sonar_frontend << ", estimator_mode=" << config.estimator_mode << ")\n";
  }
  if (opt.max_iterations > 0) defaults.max_iterations = opt.max_iterations;  // CLI wins last

  // Single ordered pass over the bag (docs/archive/superpowers/plans/2026-08-24-
  // live-replay-unified-ingress.md Task 4): every ReadMcapMessages<T> call
  // this function used to make per-topic, per-payload-type is now a filter
  // over this one ReplayInputData -- see each consumption point below for
  // how its original filter is reproduced on the flattened vectors.
  uw::runtime::McapEventSource event_source(opt.bag_path);
  uw::application::ReplayInputAccumulator accumulator;
  const auto pump_report = uw::application::PumpEvents(event_source, accumulator);
  if (pump_report.status == uw::runtime::EventSourceStatus::kOpenFailed) {
    std::cerr << "failed to open bag: " << opt.bag_path << "\n";
    return 1;
  }
  if (pump_report.unknown_topic_count > 0 || pump_report.parse_failure_count > 0) {
    std::cout << "warning: bag scan saw " << pump_report.unknown_topic_count
              << " unknown-topic message(s) and " << pump_report.parse_failure_count
              << " topic/schema-mismatched message(s) (see EventSourceReport)\n";
  }
  if (accumulator.Diagnostics().HasErrors()) {
    std::cerr << "replay input identity error(s):\n";
    for (const auto& message : accumulator.Diagnostics().messages) std::cerr << "  - " << message << "\n";
    return 1;
  }
  const uw::application::ReplayInputData& input = accumulator.Data();

  // Rectify once, up front: everything downstream that consumes camera
  // frames (stereo_landmark_vo_frontend, stereo_optical_depth_frontend, and
  // therefore the acoustic-optic fusion/map-bridge chain built on top of it)
  // now hard-requires is_rectified()==true input (StereoGeometry::Resolve's
  // rectified-pair contract — see sensor_models/camera_model.hpp). A failed
  // Create() here means this rig cannot be rectified at all, so every
  // camera-dependent pass below would silently produce zero evidence;
  // failing the whole run immediately is more honest than that.
  std::optional<uw::opencv_adapters::StereoRectificationContext> rectification_context;
  if (rig.has_value()) {
    uw::opencv_adapters::StereoRectificationParams rectification_params;
    rectification_params.alpha = defaults.stereo_rectification.alpha;
    rectification_params.rectified_frame_suffix = defaults.stereo_rectification.frame_suffix;
    rectification_params.crop_policy =
        defaults.stereo_rectification.crop_policy == "common_valid_roi"
            ? uw::opencv_adapters::RectificationCropPolicy::kCommonValidRoi
            : uw::opencv_adapters::RectificationCropPolicy::kFullCanvas;
    std::string rectification_error;
    rectification_context = uw::opencv_adapters::StereoRectificationContext::Create(
        *rig, rectification_params, &rectification_error);
    if (!rectification_context.has_value()) {
      std::cerr << "stereo rectification failed: " << rectification_error << "\n";
      return 1;
    }
  }

  // Warmup window (defaults.warmup_seconds, 0 = disabled): translate to a
  // keyframe-count cutoff using synth_bag_gen's fixed 5 Hz keyframe spacing
  // ("kf0", "kf1", ... one every kKeyframeIntervalS). This is the one place
  // left in this file that still assumes that naming/spacing convention —
  // every other keyframe identity below comes straight from
  // ReplayInputData (wire observation ids), never from time. Keyframes
  // inside the window still
  // enter the graph and still get relative-pose (dead-reckoning) factors —
  // dead reckoning through the warmup period is exactly what a real
  // estimator keeps doing while it isn't yet trusting absolute corrections
  // — but they do NOT get sonar-range or depth factors (the two "absolute
  // reference" factor types below skip them). This is the batch-pose-graph
  // analogue of "don't fuse absolute fixes until the VIO's bias has settled"
  // (see defaults.warmup_seconds' doc comment in runtime/include/uw/
  // runtime/config.hpp for where the idea came from).
  //
  // kf0 stays the fixed anchor regardless of warmup_seconds: re-anchoring
  // to a later keyframe would require knowing that keyframe's true x/y/yaw,
  // which nothing in this graph observes (x/y/yaw are genuine gauge freedom
  // — see below) — only kf0 gets to use Identity() for those because
  // synth_bag_gen places kf0 at the world-frame origin by construction, not
  // because "first keyframe" is special in general.
  constexpr double kKeyframeIntervalS = 0.2;  // matches synth_bag_gen's 5 Hz spacing
  const int warmup_keyframes = defaults.warmup_seconds > 0.0
                                    ? static_cast<int>(std::ceil(defaults.warmup_seconds / kKeyframeIntervalS))
                                    : 0;
  std::unordered_set<std::string> warmup_keyframe_ids;
  for (int i = 0; i < warmup_keyframes; ++i) warmup_keyframe_ids.insert("kf" + std::to_string(i));
  if (warmup_keyframes > 0) {
    std::cout << "warmup_seconds=" << defaults.warmup_seconds << " -> " << warmup_keyframes
              << " keyframes dead-reckoned only (no sonar/depth fusion)\n";
  }

  // Gauge choice for the fixed anchor keyframe "kf0": x/y/yaw are genuine
  // gauge freedom for a relative-pose + range-only graph (nothing observes
  // an absolute horizontal position or heading), so identity is a fine
  // arbitrary choice for those. z is NOT gauge freedom once a depth factor
  // is in the graph — the depth sensor gives every keyframe (including
  // kf0) an absolute reference. Fixing kf0's z at 0 while depth factors
  // pull every other keyframe toward -measured_depth creates a genuine
  // constraint conflict (this was found by running the demo: the solver
  // stalled and ATE was several meters, not the sub-decimeter error a
  // clean synthetic scenario with this little noise should produce).
  // Anchoring kf0's z from its own depth measurement keeps the fixed
  // keyframe consistent with the rest of the graph — this is independent of
  // warmup_seconds: it directly seeds the fixed vertex rather than adding a
  // depth factor, so it's not one of the "fusions" warmup gates.
  //
  // In estimator_mode: imu_preintegration the anchor is the FIRST KEYFRAME
  // BOUNDARY's keyframe, not the literal id "kf0": keyframe identity in
  // that mode comes from /keyframe/boundary and nothing else. Its x/y/yaw
  // are the same canonical zero for the same gauge reason; its roll/pitch
  // come from the stationary initializer's measured gravity direction (the
  // one thing gravity does observe), and its z from its own depth evidence
  // exactly as below.
  const bool imu_mode = estimator_mode == "imu_preintegration";
  std::vector<const uw::domain::KeyframeBoundary*> ordered_boundaries;
  std::optional<uw::frontends::ImuStationaryInitialization> inertial_initialization;
  std::string anchor_keyframe_id = "kf0";
  if (imu_mode) {
    if (!imu_rig.has_value()) {
      std::cerr << "imu_preintegration: no rig loaded; this mode needs --experiment with a rig "
                   "carrying imu_noise and a base_link->imu_link edge\n";
      return 1;
    }
    // ReplayInputAccumulator already rejected duplicate ids and
    // non-increasing capture times, so bag order IS boundary order here;
    // this only records it.
    for (const auto& boundary : input.keyframe_boundaries) ordered_boundaries.push_back(&boundary);
    if (ordered_boundaries.size() < 2) {
      std::cerr << "imu_preintegration: fewer than two keyframe boundaries on "
                << uw::runtime::kTopicKeyframeBoundary << " (" << ordered_boundaries.size()
                << " found) — this mode has no other source of keyframe identity, and ground "
                   "truth is not a substitute\n";
      return 1;
    }
    anchor_keyframe_id = ordered_boundaries.front()->keyframe_id().value();

    const double window_end_s =
        uw::domain::ToSeconds(ordered_boundaries.front()->header().capture_time());
    inertial_initialization = uw::frontends::InitializeFromStationaryWindow(
        input.imu_samples, window_end_s, *imu_rig);
    if (!inertial_initialization.has_value()) {
      std::cerr << "imu_preintegration: cannot define an initial inertial prior from this bag "
                   "(rig imu_noise unusable, or a malformed IMU reading inside the pre-roll "
                   "window)\n";
      return 1;
    }
    std::cout << "imu stationary initializer: "
              << (inertial_initialization->mode ==
                          uw::frontends::ImuStationaryInitialization::Mode::kStationary
                      ? "stationary"
                      : "wide_velocity_prior")
              << " over " << inertial_initialization->sample_count << " sample(s) / "
              << inertial_initialization->window_duration_s << " s before "
              << anchor_keyframe_id;
    if (!inertial_initialization->detail.empty()) {
      std::cout << " (" << inertial_initialization->detail << ")";
    }
    std::cout << "\n";
  }

  double anchor_z = 0.0;
  for (const auto& evidence : input.evidence) {
    if (anchor_z != 0.0) break;  // already found
    if (!uw::domain::HasPayload<uw::domain::PressureDepthMeasurement>(evidence)) continue;
    if (evidence.source_observations_size() == 0) continue;
    if (evidence.source_observations(0).value() != anchor_keyframe_id) continue;
    // depth_m is positive-down (world Z-up); negate to get pose z — see
    // PressureDepthMeasurement's field comment in
    // schemas/proto/uw/domain/measurement.proto.
    anchor_z = -uw::domain::GetPayload<uw::domain::PressureDepthMeasurement>(evidence).depth_m();
  }

  uw::estimation::PoseGraphProblem problem;
  Pose3 anchor_pose = Pose3::Identity();
  anchor_pose.translation.z() = anchor_z;
  if (imu_mode) anchor_pose.rotation = inertial_initialization->rotation_WB;
  problem.AddKeyframe(anchor_keyframe_id, anchor_pose, /*fixed=*/true);

  // sqrt-information constants, from configs/defaults/platform.yaml via
  // --experiment (or PlatformDefaultsConfig's built-in fallback values if
  // --experiment wasn't passed). See file header limitation note: these
  // are still fixed constants, not a calibrated reliability scheduler.
  const double relative_pose_translation_cap = defaults.default_sqrt_information.relative_pose.translation;
  const double relative_pose_rotation_cap = defaults.default_sqrt_information.relative_pose.rotation;
  // FactorCandidate.proposed_noise is a single wire scalar (see
  // RelativePoseFactorBuilder::Build()'s own comment) -- set it to the max
  // of the two typed caps so it never tightens either one below what the
  // builder itself was already constructed with.
  const double relative_pose_sqrt_info = std::max(relative_pose_translation_cap, relative_pose_rotation_cap);
  const double sonar_range_sqrt_info = defaults.default_sqrt_information.sonar_range;
  const double depth_sqrt_info = defaults.default_sqrt_information.depth;

  uw::factor_builders::RelativePoseFactorBuilder relative_pose_builder(relative_pose_translation_cap,
                                                                       relative_pose_rotation_cap);
  uw::factor_builders::SonarRangeFactorBuilder sonar_range_builder;
  uw::factor_builders::DepthFactorBuilder depth_builder;

  // Online landmark store for the sonar range factor's data association
  // (see file header). All discovered landmarks live in one "landmarks"
  // bucket at a fixed Identity pose, since QueryNearestPoint/
  // WorldPointsForKeyframe already store/return world-frame points — see
  // include/mapping/submap_manager.hpp. Declared here (not down by
  // StateStore below) because it needs to be live during the sonar
  // evidence pass, not just after solving.
  uw::mapping::SubmapManager submap_manager;
  submap_manager.UpdateKeyframePose("landmarks", Pose3::Identity());
  int next_landmark_id = 0;
  int num_landmarks_discovered = 0;

  // Camera frames, partitioned once and shared by both the relative-pose
  // block below (estimator_mode == "stereo_landmark_vo") and the acoustic-
  // optic pass further down — both used to read these topics independently
  // before this migration. Frames stay RAW here: the synchronizer and sonar
  // frontend still consume raw sonar/raw image headers (capture_time,
  // sensor_frame) per this file's acoustic-optic pass, only the rectified/
  // MONO8 pixel content is derived on demand below via get_rectified().
  //
  // Identity comes straight from header.observation_id (ImageFrame.header,
  // set by synth_bag_gen's BuildStereoPair / record_session.py's
  // _write_keyframe) — no capture_time-based reconstruction. left/right are
  // told apart by header.sensor_id ("camera_left"/"camera_right"), the same
  // convention both producers already use.
  std::unordered_map<std::string, uw::domain::ImageFrame> left_by_kf_raw, right_by_kf_raw;
  // First-appearance order of camera keyframe ids, in the bag's log_time_ns
  // order (McapEventSource) — replaces the old "kf" + std::to_string(i) for
  // i in [0, max_kf_index] loop, which assumed contiguous numeric ids.
  std::vector<std::string> ordered_camera_keyframe_ids;
  std::unordered_set<std::string> seen_camera_keyframe_ids;

  // Real per-keyframe metadata for StateSnapshot/TUM output (P1: no more
  // `index * kKeyframeIntervalS` timestamp fabrication). Priority for
  // capture_time_by_keyframe, highest first: raw left camera capture_time
  // (set here) > /gt/state's own capture_timestamp, matched by state_id
  // (set below, before the snapshot loop) > the MCAP log_time_ns of
  // whatever relative-pose/depth evidence first referenced this keyframe
  // (set in those read passes below) -- each tier only fills a keyframe
  // that a higher tier left unset.
  std::unordered_map<std::string, uw::domain::Stamp> capture_time_by_keyframe;
  std::unordered_map<std::string, std::vector<uw::domain::EvidenceId>> evidence_by_keyframe;

  if (rig.has_value()) {
    for (const auto& frame : input.images) {
      const std::string& kf_id = frame.header().observation_id().value();
      const std::string& sensor_id = frame.header().sensor_id().value();
      if (sensor_id == "camera_left") {
        left_by_kf_raw[kf_id] = frame;
        capture_time_by_keyframe[kf_id] = frame.header().capture_time();
      } else if (sensor_id == "camera_right") {
        right_by_kf_raw[kf_id] = frame;
      } else {
        continue;
      }
      if (seen_camera_keyframe_ids.insert(kf_id).second) ordered_camera_keyframe_ids.push_back(kf_id);
    }
  }

  // Rectifies (ConvertToMono8 + StereoRectificationContext::Process()) a
  // keyframe's raw stereo pair at most once, caching the result so the VO
  // pass and the acoustic-optic pass below never remap the same pixels
  // twice. Returns nullptr if the raw pair is missing or fails
  // ConvertToMono8/Process() (e.g. wrong encoding, size mismatch) — a
  // per-keyframe condition, not a fatal error like a failed Create() above.
  std::unordered_map<std::string, uw::opencv_adapters::RectifiedStereoBundle> rectified_by_kf;
  auto get_rectified = [&](const std::string& kf_id) -> uw::opencv_adapters::RectifiedStereoBundle* {
    const auto cached = rectified_by_kf.find(kf_id);
    if (cached != rectified_by_kf.end()) return &cached->second;
    const auto left_it = left_by_kf_raw.find(kf_id);
    const auto right_it = right_by_kf_raw.find(kf_id);
    if (left_it == left_by_kf_raw.end() || right_it == right_by_kf_raw.end()) return nullptr;
    const auto left_mono = uw::domain::ConvertToMono8(left_it->second);
    const auto right_mono = uw::domain::ConvertToMono8(right_it->second);
    if (!left_mono.has_value() || !right_mono.has_value()) return nullptr;
    std::string process_error;
    auto rectified = rectification_context->Process(*left_mono, *right_mono, &process_error);
    if (!rectified.has_value()) return nullptr;
    return &rectified_by_kf.emplace(kf_id, std::move(*rectified)).first->second;
  };

  // Per-keyframe VO health AT THE TIME that keyframe was processed --
  // black-box mode never populates this (no local VO frontend to ask), so
  // DecideTrackingStatus's vo_enabled must be false for those snapshots.
  std::unordered_map<std::string, uw::domain::HealthReport::Status> vo_health_by_keyframe;

  // Fills the remaining capture_time_by_keyframe priority tiers below raw
  // camera capture_time (already set above, unconditionally, when it
  // exists): GT's own real capture_timestamp (matched by state_id -- a
  // genuine timestamp field this platform's synthetic/real bags already
  // carry, used here for TIMING only, never for pose -- ground truth still
  // never enters estimated state), then the MCAP log_time_ns of whichever
  // depth/relative-pose evidence first referenced a keyframe, as a last
  // resort. .emplace() only inserts when a higher tier hasn't already
  // claimed that keyframe, so running these three passes in this fixed
  // order IS the priority order.
  //
  // In estimator_mode: imu_preintegration none of that applies: the
  // /keyframe/boundary stream is the sole source of both keyframe identity
  // and keyframe time, filled here ahead of every other tier, and the
  // ground-truth loop below contributes NOTHING to the algorithm path --
  // not a pose, and not a timestamp either. A timestamp is not a harmless
  // thing to take from ground truth in this mode: it is what defines the
  // preintegration interval, so reading it from /gt/state would put ground
  // truth directly into the estimate.
  if (imu_mode) {
    for (const auto* boundary : ordered_boundaries) {
      capture_time_by_keyframe[boundary->keyframe_id().value()] = boundary->header().capture_time();
    }
  }
  std::vector<uw::evaluation::TrajectoryPose> ground_truth_trajectory;
  for (const auto& gt : input.reference_states) {
    if (!imu_mode && gt.has_state_id() && !gt.state_id().value().empty()) {
      capture_time_by_keyframe.emplace(gt.state_id().value(), gt.capture_timestamp());
    }
    ground_truth_trajectory.push_back(
        {uw::domain::ToSeconds(gt.capture_timestamp()), Pose3::FromProto(gt.pose_wb())});
  }
  int num_timestamp_fallback_evidence = 0;
  for (std::size_t i = 0; i < input.evidence.size() && !imu_mode; ++i) {
    const auto& evidence = input.evidence[i];
    if (!uw::domain::HasPayload<uw::domain::PressureDepthMeasurement>(evidence)) continue;
    if (evidence.source_observations_size() == 0) continue;
    const auto log_time_ns = accumulator.EvidenceLogTimeNs()[i];
    const auto [it, inserted] = capture_time_by_keyframe.emplace(
        evidence.source_observations(0).value(),
        uw::domain::FromSeconds(static_cast<double>(log_time_ns) * 1e-9));
    if (inserted) ++num_timestamp_fallback_evidence;
  }
  for (std::size_t i = 0; i < input.evidence.size() && !imu_mode; ++i) {
    const auto& evidence = input.evidence[i];
    if (!uw::domain::HasPayload<uw::domain::RelativePoseMeasurement>(evidence)) continue;
    const auto& measurement = uw::domain::GetPayload<uw::domain::RelativePoseMeasurement>(evidence);
    const auto log_time_ns = accumulator.EvidenceLogTimeNs()[i];
    const auto [it, inserted] = capture_time_by_keyframe.emplace(
        measurement.to_keyframe().value(), uw::domain::FromSeconds(static_cast<double>(log_time_ns) * 1e-9));
    if (inserted) ++num_timestamp_fallback_evidence;
  }
  if (num_timestamp_fallback_evidence > 0) {
    std::cout << "warning: " << num_timestamp_fallback_evidence
              << " keyframe(s) had no camera/GT timestamp; used MCAP log_time_ns as a fallback\n";
  }

  // One shared tail for every relative-pose factor source below -- bag
  // evidence (black_box_vio), stereo VO, and loop closure all produce the
  // same RelativePoseMeasurement payload and differ only in where the
  // evidence came from and how the edge enters the graph:
  //   - sequential edges (VO, bag evidence) dead-reckon their `to` keyframe
  //     into the graph as the initial guess the solver later refines;
  //   - loop edges run AFTER dead reckoning has populated the graph, so they
  //     require `to` to already exist and carry a robust policy instead.
  // Returns true iff a factor was actually added.
  auto add_relative_pose_edge =
      [&](const uw::domain::MeasurementEvidence& evidence, bool dead_reckon_to,
          uw::estimation::PoseGraphProblem::RobustPolicy robust_policy) -> bool {
    const auto& measurement =
        uw::domain::GetPayload<uw::domain::RelativePoseMeasurement>(evidence);
    const std::string from = measurement.from_keyframe().value();
    const std::string to = measurement.to_keyframe().value();
    if (!problem.HasKeyframe(from)) return false;  // out-of-order/unexpected input: skip, don't guess
    if (dead_reckon_to) {
      const auto measured_relative = Pose3::FromProto(measurement.relative_pose());
      problem.AddKeyframe(to, problem.GetKeyframePose(from) * measured_relative);
    } else if (!problem.HasKeyframe(to)) {
      return false;
    }

    uw::domain::FactorCandidate candidate;
    candidate.set_residual_model(uw::factor_builders::RelativePoseFactorBuilder::kResidualModel);
    candidate.set_proposed_noise(relative_pose_sqrt_info);
    if (robust_policy == uw::estimation::PoseGraphProblem::RobustPolicy::kHuber) {
      candidate.set_robust_policy_hint(uw::domain::ROBUST_POLICY_HUBER);
    }
    auto block = relative_pose_builder.Build(candidate, evidence, {});
    if (!block) return false;
    problem.AddResidualBlock(std::move(block), {from, to}, robust_policy);
    evidence_by_keyframe[to].push_back(evidence.evidence_id());
    return true;
  };

  int num_relative_pose_factors = 0;
  int num_imu_factors = 0;
  int num_imu_intervals_rejected = 0;
  if (imu_mode) {
    // Inertial dead reckoning. Nothing in this branch reads /gt/state or a
    // RelativePoseMeasurement: every keyframe after the anchor gets its
    // pose AND velocity purely from the previous ESTIMATED state propagated
    // through this interval's preintegrated delta, which is the only
    // initial guess a phase-1 sensor set can legitimately produce.
    //
    // Delta definitions (sensor_models/imu_preintegration.hpp), inverted to
    // propagate forward with g_W = (0, 0, -gravity):
    //   R_j = R_i dR        v_j = v_i + g dt + R_i dv
    //   p_j = p_i + v_i dt + 0.5 g dt^2 + R_i dp
    uw::frontends::ImuPreintegrationFrontendParams imu_params;
    uw::frontends::ImuPreintegrationFrontend imu_frontend(imu_params);
    uw::factor_builders::ImuPreintegrationFactorBuilder imu_builder;
    const double gravity_mps2 = imu_rig->imu_noise().gravity_mps2() > 0.0
                                    ? imu_rig->imu_noise().gravity_mps2()
                                    : 9.80665;
    const Eigen::Vector3d gravity_W(0.0, 0.0, -gravity_mps2);

    // The anchor's POSE is fixed (gauge), but its inertial block is not:
    // velocity and both biases are quantities the solver is meant to
    // refine. What holds them is the one prior residual added below --
    // without it the block is structurally unconstrained and the normal
    // equations are singular.
    uw::estimation::PoseGraphProblem::InertialState anchor_inertial;
    anchor_inertial.velocity_W = inertial_initialization->velocity_W;
    anchor_inertial.bias_gyro = inertial_initialization->bias_gyro;
    anchor_inertial.bias_accel = inertial_initialization->bias_accel;
    problem.AddInertialState(anchor_keyframe_id, anchor_inertial);

    Eigen::Matrix<double, 9, 1> prior_target;
    prior_target.segment<3>(0) = anchor_inertial.velocity_W;
    prior_target.segment<3>(3) = anchor_inertial.bias_gyro;
    prior_target.segment<3>(6) = anchor_inertial.bias_accel;
    auto prior_block = uw::factor_builders::InertialPriorResidual::Create(
        prior_target, inertial_initialization->sigma);
    if (!prior_block) {
      std::cerr << "imu_preintegration: the stationary initializer produced a prior sigma that "
                   "cannot define a residual\n";
      return 1;
    }
    problem.AddResidualBlockOnParameters(
        std::move(prior_block),
        {uw::estimation::PoseGraphProblem::InertialRef(anchor_keyframe_id)});

    // Sorted once, then sliced per interval. Handing the frontend the whole
    // bag every time is quadratic: it re-filters, re-converts and re-sorts
    // every sample on every call, so a 5-minute recording at 200 Hz with
    // 5 Hz keyframes would do ~1500 full sorts of 60000 samples. The
    // synthetic fixture (541 samples, 11 intervals) hides that completely.
    // The slice starts at the last sample at or before `from_time` -- the
    // reading the frontend holds at the interval's start -- and ends at
    // `to_time`, which is everything it looks at.
    std::vector<uw::domain::ImuSample> sorted_imu_samples = input.imu_samples;
    std::stable_sort(sorted_imu_samples.begin(), sorted_imu_samples.end(),
                     [](const uw::domain::ImuSample& a, const uw::domain::ImuSample& b) {
                       return uw::domain::ToSeconds(a.header().capture_time()) <
                              uw::domain::ToSeconds(b.header().capture_time());
                     });
    std::vector<double> sorted_imu_times;
    sorted_imu_times.reserve(sorted_imu_samples.size());
    for (const auto& sample : sorted_imu_samples) {
      sorted_imu_times.push_back(uw::domain::ToSeconds(sample.header().capture_time()));
    }
    auto imu_window_for = [&](double from_time_s,
                              double to_time_s) -> std::vector<uw::domain::ImuSample> {
      const auto first_after_from =
          std::upper_bound(sorted_imu_times.begin(), sorted_imu_times.end(), from_time_s);
      const std::size_t begin =
          first_after_from == sorted_imu_times.begin()
              ? 0
              : static_cast<std::size_t>(first_after_from - sorted_imu_times.begin()) - 1;
      const auto first_after_to =
          std::upper_bound(sorted_imu_times.begin(), sorted_imu_times.end(), to_time_s);
      const std::size_t end = static_cast<std::size_t>(first_after_to - sorted_imu_times.begin());
      if (end <= begin) return {};
      return std::vector<uw::domain::ImuSample>(sorted_imu_samples.begin() + begin,
                                                 sorted_imu_samples.begin() + end);
    };

    for (std::size_t i = 1; i < ordered_boundaries.size(); ++i) {
      const std::string from = ordered_boundaries[i - 1]->keyframe_id().value();
      const std::string to = ordered_boundaries[i]->keyframe_id().value();
      if (!problem.HasKeyframe(from)) {
        ++num_imu_intervals_rejected;
        continue;  // the previous interval was rejected; do not bridge over it
      }

      uw::measurement_api::ImuPreintegrationRequest request;
      request.from_keyframe_id = from;
      request.to_keyframe_id = to;
      request.from_time = ordered_boundaries[i - 1]->header().capture_time();
      request.to_time = ordered_boundaries[i]->header().capture_time();
      // Linearise at the state the graph currently holds for `from`, which
      // for the anchor is the initializer's estimate and afterwards is the
      // propagated one.
      const auto from_inertial = problem.GetInertialState(from);
      request.bias_gyro = from_inertial.bias_gyro;
      request.bias_accel = from_inertial.bias_accel;

      const auto evidence = imu_frontend.Process(
          imu_window_for(uw::domain::ToSeconds(request.from_time),
                         uw::domain::ToSeconds(request.to_time)),
          request, *imu_rig);
      if (!evidence.has_value()) {
        ++num_imu_intervals_rejected;
        std::cout << "imu interval " << from << " -> " << to
                  << " rejected: " << imu_frontend.last_rejection_reason() << "\n";
        continue;
      }
      std::string delta_error;
      const auto delta = uw::sensor_models::PreintegratedImuDelta::FromProto(
          evidence->imu_preintegration(), &delta_error);
      if (!delta.has_value()) {
        ++num_imu_intervals_rejected;
        std::cout << "imu interval " << from << " -> " << to
                  << " rejected: unreadable delta (" << delta_error << ")\n";
        continue;
      }

      const Pose3 from_pose = problem.GetKeyframePose(from);
      const Eigen::Matrix3d R_i = from_pose.rotation.toRotationMatrix();
      const double dt = delta->delta_time_s;
      Pose3 to_pose;
      to_pose.rotation = Eigen::Quaterniond(R_i * delta->delta_rotation).normalized();
      to_pose.translation = from_pose.translation + from_inertial.velocity_W * dt +
                            0.5 * gravity_W * dt * dt + R_i * delta->delta_position;
      uw::estimation::PoseGraphProblem::InertialState to_inertial;
      to_inertial.velocity_W =
          from_inertial.velocity_W + gravity_W * dt + R_i * delta->delta_velocity;
      // Biases are modelled as a random walk, so the propagated guess for
      // the next state is simply the current one; the IMU residual's bias
      // rows are what let the solver move them apart.
      to_inertial.bias_gyro = from_inertial.bias_gyro;
      to_inertial.bias_accel = from_inertial.bias_accel;

      uw::domain::FactorCandidate candidate;
      candidate.set_residual_model(
          uw::factor_builders::ImuPreintegrationFactorBuilder::kResidualModel);
      candidate.set_proposed_noise(1.0);
      auto block = imu_builder.Build(candidate, *evidence, {});
      if (!block) {
        ++num_imu_intervals_rejected;
        std::cout << "imu interval " << from << " -> " << to
                  << " rejected: factor builder refused the evidence\n";
        continue;
      }

      // Registered only now that the edge is certain to exist. Adding the
      // keyframe first and bailing out afterwards would leave `to` in the
      // graph with a free 9-dim inertial block and no IMU edge, which both
      // defeats the "did the previous interval survive?" guard above (the
      // next iteration would find `to` present and bridge straight over the
      // gap) and, if `to` has no depth/sonar factor either, turns a
      // recoverable interval rejection into a hard structural failure.
      problem.AddKeyframe(to, to_pose);
      problem.AddInertialState(to, to_inertial);
      problem.AddResidualBlockOnParameters(
          std::move(block), {uw::estimation::PoseGraphProblem::PoseRef(from),
                             uw::estimation::PoseGraphProblem::InertialRef(from),
                             uw::estimation::PoseGraphProblem::PoseRef(to),
                             uw::estimation::PoseGraphProblem::InertialRef(to)});
      evidence_by_keyframe[to].push_back(evidence->evidence_id());
      ++num_imu_factors;
    }
    std::cout << "added " << num_imu_factors << " IMU preintegration factors over "
              << ordered_boundaries.size() << " keyframe boundaries ("
              << num_imu_intervals_rejected << " interval(s) rejected)\n";
    // A rejected interval does not merely lose one edge: with no other
    // relative-motion source in this sensor set, `to` never enters the
    // graph and neither does anything after it. The run would then write a
    // SHORTER trajectory and score an ATE over that prefix alone -- which
    // can read better than the full run, not worse. Fail closed instead of
    // publishing a number that silently describes a different trajectory
    // than the one that was asked for.
    if (problem.NumKeyframes() != ordered_boundaries.size()) {
      std::cerr << "imu_preintegration: " << problem.NumKeyframes() << " of "
                << ordered_boundaries.size()
                << " keyframe boundaries made it into the graph — " << num_imu_intervals_rejected
                << " interval(s) were rejected, so the trajectory is truncated and any ATE over "
                   "it would describe a different run\n";
      return 1;
    }
  } else if (rig.has_value() && estimator_mode == "stereo_landmark_vo") {
    // Real relative-pose evidence computed from stereo camera frames
    // (include/frontends/stereo_landmark_vo_frontend.hpp) instead of
    // synth_bag_gen's ground-truth+noise "black-box VIO" stand-in read
    // from /evidence/relative_pose below. Keyframes must be visited in
    // order (the frontend is stateful across calls, comparing this call's
    // landmarks to the previous one's) — iterate kf0..kfN in order rather
    // than relying on bag stream order.
    uw::frontends::StereoLandmarkVoFrontendParams vo_params;
    vo_params.left_frame = rectification_context->LeftRectifiedFrame();
    vo_params.right_frame = rectification_context->RightRectifiedFrame();
    vo_params.max_consecutive_failures = defaults.visual_odometry.max_consecutive_failures;
    vo_params.covariance_estimation.max_condition_number = defaults.visual_odometry.max_condition_number;
    vo_params.covariance_estimation.residual_variance_floor_m2 =
        defaults.visual_odometry.residual_variance_floor_m2;
    vo_params.covariance_estimation.max_inlier_rmse_m = defaults.visual_odometry.max_inlier_rmse_m;
    vo_params.detector_kind = landmark_detector == "harris_corner"
                                   ? uw::frontends::LandmarkDetectorKind::kHarrisCorner
                                   : uw::frontends::LandmarkDetectorKind::kBrightBlob;
    if (landmark_detector == "harris_corner") {
      // Only for the real-camera path: synth_bag_gen's landmarks are
      // deliberately unique per-id hash patterns (see its header), so
      // PatchMatcher's plain greedy NCC never had an ambiguity problem
      // there and the tracked synthetic ATE number shouldn't shift.
      // Real underwater imagery (coral/rock/sand) is locally repetitive —
      // confirmed the hard way running apps/replay_demo against a real
      // HoloOcean recording: appearance-only matching with no
      // spatial/distinctiveness constraint produced ATE=587m (solver
      // stalled), because RANSAC's majority-consensus assumption breaks
      // down once wrong correspondences are as numerous as right ones.
      // max_row_diff_px mirrors BlockMatcher's own same-row disparity
      // search (an epipolar constraint for this rig's parallel stereo
      // pair); min_score_margin rejects a match unless it is clearly
      // better than the next-best candidate for either side (a
      // Lowe's-ratio-test-style distinctiveness check) — see
      // patch_matcher.hpp for both. Thresholds are a first empirical pass
      // against the one real bag available, not a calibrated constant.
      vo_params.stereo_matcher.max_row_diff_px = 4.0;
      vo_params.stereo_matcher.min_score_margin = 0.02;
      vo_params.temporal_matcher.min_score_margin = 0.05;
    }
    uw::frontends::StereoLandmarkVoFrontend vo_frontend(vo_params);

    for (const auto& kf_id : ordered_camera_keyframe_ids) {
      auto* rectified = get_rectified(kf_id);
      if (rectified == nullptr) continue;

      uw::measurement_api::CameraFrameBundle bundle = rectified->images;
      bundle.primary.mutable_header()->mutable_observation_id()->set_value(kf_id);

      const auto vo_evidence = vo_frontend.Process(bundle, rectification_context->DerivedRig());
      // Recorded for EVERY processed frame, success or failure, keyed by
      // the frame that was just processed -- this is what makes
      // DecideTrackingStatus's per-snapshot VO health non-retroactive (a
      // keyframe processed while VO was still healthy must stay TRACKING
      // even if VO later degrades).
      vo_health_by_keyframe[kf_id] = vo_frontend.Health().status();
      if (!vo_evidence.has_value()) continue;  // first frame seen, or couldn't fit this transition
      if (add_relative_pose_edge(*vo_evidence, /*dead_reckon_to=*/true,
                                 uw::estimation::PoseGraphProblem::RobustPolicy::kNone)) {
        ++num_relative_pose_factors;
      }
    }
    std::cout << "stereo_landmark_vo_frontend: computed relative-pose evidence from camera frames "
                 "(estimator_mode=stereo_landmark_vo)\n";
  } else {
    for (const auto& evidence : input.evidence) {
      if (!uw::domain::HasPayload<uw::domain::RelativePoseMeasurement>(evidence)) continue;
      if (add_relative_pose_edge(evidence, /*dead_reckon_to=*/true,
                                 uw::estimation::PoseGraphProblem::RobustPolicy::kNone)) {
        ++num_relative_pose_factors;
      }
    }
  }
  std::cout << "added " << num_relative_pose_factors << " relative-pose factors, "
            << problem.NumKeyframes() << " keyframes\n";

  // Loop-closure pose-graph edges (architecture-inspired by SVIn's
  // pose_graph module — see frontends/loop_closure_frontend.hpp's own
  // header comment for what was and wasn't ported). A second pass, AFTER
  // the stereo_landmark_vo loop above has finished dead-reckoning every
  // keyframe into `problem` — not interleaved with it — so "advance dead
  // reckoning one edge at a time" and "search the whole archive so far"
  // stay separate concerns and the archive never contains a not-yet-
  // dead-reckoned keyframe. Gated by the SAME rig/estimator_mode
  // precondition as VO (loop closure needs real camera frames) plus
  // defaults.loop_closure.enabled (default off — zero behavior change to
  // any existing experiment unless a config explicitly opts in).
  int num_loop_closure_factors = 0;
  if (rig.has_value() && estimator_mode == "stereo_landmark_vo" && defaults.loop_closure.enabled) {
    uw::frontends::LoopClosureFrontendParams lc_params;
    lc_params.left_frame = rectification_context->LeftRectifiedFrame();
    lc_params.right_frame = rectification_context->RightRectifiedFrame();
    lc_params.candidate_search_radius_m = defaults.loop_closure.candidate_search_radius_m;
    lc_params.min_keyframe_index_gap = defaults.loop_closure.min_keyframe_index_gap;
    lc_params.max_accepted_translation_m = defaults.loop_closure.max_accepted_translation_m;
    lc_params.max_accepted_rotation_rad = defaults.loop_closure.max_accepted_rotation_rad;
    lc_params.min_landmarks_for_pose = defaults.loop_closure.min_landmarks_for_pose;
    lc_params.max_loop_edges_per_keyframe = defaults.loop_closure.max_loop_edges_per_keyframe;
    uw::frontends::LoopClosureFrontend loop_frontend(lc_params);

    for (const auto& kf_id : ordered_camera_keyframe_ids) {
      if (!problem.HasKeyframe(kf_id)) continue;  // VO never dead-reckoned this one (e.g. the first frame)
      auto* rectified = get_rectified(kf_id);
      if (rectified == nullptr) continue;

      uw::measurement_api::CameraFrameBundle bundle = rectified->images;
      bundle.primary.mutable_header()->mutable_observation_id()->set_value(kf_id);

      // problem.GetKeyframePose(kf_id) here is still the PRE-SOLVE
      // dead-reckoned estimate (solver.Solve() hasn't run yet) — exactly
      // the "position at insertion time" pose-proximity search needs.
      const auto loop_evidences =
          loop_frontend.Process(bundle, rectification_context->DerivedRig(), kf_id, problem.GetKeyframePose(kf_id));
      for (const auto& loop_evidence : loop_evidences) {
        if (add_relative_pose_edge(loop_evidence, /*dead_reckon_to=*/false,
                                   uw::estimation::PoseGraphProblem::RobustPolicy::kHuber)) {
          ++num_loop_closure_factors;
        }
      }
    }
    std::cout << "loop_closure_frontend: added " << num_loop_closure_factors << " loop-closure factors\n";
  }

  const auto cfar_params =
      uw::application::BuildSonarCfarFrontendParams(defaults.sonar_frontend);
  uw::frontends::SonarCfarFrontend sonar_frontend(cfar_params);

  int num_sonar_frames = 0;
  int num_sonar_factors = 0;
  // Per-sonar-frame processing latency, mirroring
  // acoustic_optic_scenario_matrix.cpp's per-trial
  // timing pattern. This loop (not the stereo_landmark_vo loop above,
  // which only runs in VO mode, and not any single point elsewhere in this
  // multi-pass batch file) is the one genuinely per-keyframe frontend +
  // data-association + factor-building pass that runs in every experiment
  // config regardless of estimator_mode — the natural place for a first
  // latency proxy. This is groundwork, not real online latency:
  // replay_demo processes a whole bag in a few batch passes, so this
  // measures per-frame CPU cost within that batch, not capture-to-pose
  // latency in a live system, which requires an online scheduler.
  std::vector<double> sonar_frame_latencies_ms;
  for (const auto& frame : input.sonar_frames) {
    // RAII so every exit path below (the early `continue`s for warmup/
    // unknown-keyframe/no-detection included) gets timed, not just the
    // full-processing path — a reject decision still costs real time
    // in an online system.
    struct LatencyRecorder {
      std::vector<double>& out;
      std::chrono::steady_clock::time_point start;
      ~LatencyRecorder() {
        out.push_back(
            std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - start).count());
      }
    } latency_recorder{sonar_frame_latencies_ms, std::chrono::steady_clock::now()};

    ++num_sonar_frames;
    const std::string keyframe_id = frame.header().observation_id().value();
    if (!problem.HasKeyframe(keyframe_id)) continue;
    if (warmup_keyframe_ids.count(keyframe_id)) continue;  // dead-reckoning only during warmup

    // v1 rule (schemas/proto/uw/domain/hypothesis.proto, see file
    // header): only the top-ranked (largest-cluster) candidate is
    // consumed. candidates(0) is a full MeasurementEvidence, not just
    // the payload — reuse it as-is rather than re-wrapping via
    // domain::TopCandidate<T>(), which would discard evidence_id/
    // algorithm_version for no benefit here.
    const auto hypothesis_set = sonar_frontend.ProcessSonarFrame(frame);
    if (hypothesis_set.candidates_size() == 0) continue;  // no detection above threshold
    const auto& evidence = hypothesis_set.candidates(0);
    if (!uw::domain::HasPayload<uw::domain::SonarRangeBearing>(evidence)) continue;
    const auto& measurement = uw::domain::GetPayload<uw::domain::SonarRangeBearing>(evidence);

    // Real submap_manager query (see file header): project the
    // detection into world frame using the keyframe's CURRENT
    // (dead-reckoned, not yet optimized) pose estimate, then ask the
    // submap for an already-known landmark within kLandmarkGateM. A
    // hit reuses that landmark's stored position (stable across
    // repeated sightings, not re-derived from this noisier single
    // detection); a miss means this is a never-before-seen landmark,
    // which gets inserted so later sightings can match it.
    const auto current_pose = problem.GetKeyframePose(keyframe_id);
    const Eigen::Vector3d local_detection(measurement.range_m() * std::cos(measurement.bearing_rad()),
                                           measurement.range_m() * std::sin(measurement.bearing_rad()),
                                           0.0);  // sonar has no elevation — see file header
    const Eigen::Vector3d predicted_point_W = current_pose.Apply(local_detection);

    constexpr double kLandmarkGateM = 1.5;  // margin over expected dead-reckoning drift at these ranges
    const auto existing = submap_manager.QueryNearestPoint(predicted_point_W, kLandmarkGateM);
    Eigen::Vector3d landmark_W;
    if (existing.has_value()) {
      landmark_W = *existing;
    } else {
      landmark_W = predicted_point_W;
      uw::domain::MapEvidence landmark_evidence;
      landmark_evidence.mutable_evidence_id()->set_value("landmark_" + std::to_string(next_landmark_id++));
      landmark_evidence.mutable_keyframe_id()->set_value("landmarks");
      landmark_evidence.mutable_local_frame()->set_value("world");
      landmark_evidence.set_representation_type(uw::domain::MAP_REPRESENTATION_POINT_CLOUD);
      landmark_evidence.set_reintegration_policy(
          uw::domain::MapEvidence::REINTEGRATION_POLICY_TRANSFORM_ONLY);
      std::string bytes(3 * sizeof(float), '\0');
      auto* raw = reinterpret_cast<float*>(bytes.data());
      raw[0] = static_cast<float>(landmark_W.x());
      raw[1] = static_cast<float>(landmark_W.y());
      raw[2] = static_cast<float>(landmark_W.z());
      landmark_evidence.set_geometry_or_occupancy(bytes);
      submap_manager.AddMapEvidence(landmark_evidence);
      ++num_landmarks_discovered;
    }

    uw::domain::FactorCandidate candidate;
    candidate.set_residual_model(uw::factor_builders::SonarRangeFactorBuilder::kResidualModel);
    candidate.set_proposed_noise(sonar_range_sqrt_info);
    uw::measurement_api::FactorBuildContext context;
    context.nearby_points_W = {landmark_W};
    auto block = sonar_range_builder.Build(candidate, evidence, context);
    if (block) {
      problem.AddResidualBlock(std::move(block), {keyframe_id});
      evidence_by_keyframe[keyframe_id].push_back(evidence.evidence_id());
      ++num_sonar_factors;
    }
  }
  std::cout << "discovered " << num_landmarks_discovered << " landmarks via submap query\n";
  std::cout << "processed " << num_sonar_frames << " sonar frames (sonar_cfar_frontend) -> "
            << num_sonar_factors << " sonar range factors\n";
  // Same P95 formula as acoustic_optic_scenario_matrix.cpp (nearest-rank,
  // no interpolation) — see this block's own comment above for scope.
  std::sort(sonar_frame_latencies_ms.begin(), sonar_frame_latencies_ms.end());
  const double p95_sonar_frame_latency_ms =
      sonar_frame_latencies_ms.empty()
          ? 0.0
          : sonar_frame_latencies_ms[static_cast<std::size_t>(0.95 * (sonar_frame_latencies_ms.size() - 1))];
  std::cout << "sonar frame processing latency: p95_ms=" << p95_sonar_frame_latency_ms << "\n";

  int num_depth_factors = 0;
  for (const auto& evidence : input.evidence) {
    if (!uw::domain::HasPayload<uw::domain::PressureDepthMeasurement>(evidence)) continue;
    if (evidence.source_observations_size() == 0) continue;
    const std::string keyframe_id = evidence.source_observations(0).value();
    if (!problem.HasKeyframe(keyframe_id)) continue;
    if (warmup_keyframe_ids.count(keyframe_id)) continue;  // dead-reckoning only during warmup

    uw::domain::FactorCandidate candidate;
    candidate.set_residual_model(uw::factor_builders::DepthFactorBuilder::kResidualModel);
    candidate.set_proposed_noise(depth_sqrt_info);
    auto block = depth_builder.Build(candidate, evidence, {});
    if (block) {
      problem.AddResidualBlock(std::move(block), {keyframe_id});
      evidence_by_keyframe[keyframe_id].push_back(evidence.evidence_id());
      ++num_depth_factors;
    }
  }
  std::cout << "added " << num_depth_factors << " depth factors\n";

  // defaults.solver was already validated by ValidateExperimentConfigSelections.
  // Structural observability, checked BEFORE solving (PREP-B-01): a free
  // parameter block that no residual touches is a singular column, and LM
  // damping would return a plausible-looking arbitrary value for it rather
  // than failing. In estimator_mode: imu_preintegration this is the
  // specific guard the design note asks for -- every inertial state must be
  // reached by an IMU edge or by the anchor prior -- but the property is
  // mode-independent, so it is checked for every run.
  const auto observability = uw::application::CheckGraphObservability(problem);
  std::cout << "graph: " << problem.NumKeyframes() << " keyframes, "
            << problem.NumInertialStates() << " inertial states, "
            << problem.NumResidualBlocks() << " residual blocks, "
            << observability.free_parameter_dim << " free parameter dims, "
            << observability.residual_dim << " residual dims\n";
  if (!observability.problems.empty()) {
    std::cerr << "STRUCTURALLY SINGULAR GRAPH:\n";
    for (const auto& problem_text : observability.problems) {
      std::cerr << "  - " << problem_text << "\n";
    }
    return 1;
  }

  uw::estimation::GaussNewtonSolver solver;
  uw::estimation::GaussNewtonSolver::Options solver_options;
  solver_options.max_iterations = defaults.max_iterations;
  solver_options.initial_lambda = defaults.initial_lambda;
  // Only affects RobustPolicy::kHuber-flagged bindings (loop-closure
  // edges above); harmless no-op when none exist.
  solver_options.huber_delta = defaults.loop_closure.huber_delta;
  const uw::estimation::GaussNewtonSummary summary = solver.Solve(problem, solver_options);
  std::cout << "solver: " << summary.iterations << " iterations, cost "
            << summary.initial_cost << " -> " << summary.final_cost
            << (summary.converged ? " (converged)" : " (stalled)") << "\n";

  // StateStore wiring (submap_manager was declared earlier — it's already
  // been accumulating landmark evidence since the sonar pass above).
  uw::estimation::StateStore state_store;
  std::vector<uw::evaluation::TrajectoryPose> estimated_trajectory;

  const std::string calibration_version_for_snapshot =
      rectification_context.has_value() ? rectification_context->DerivedRig().calibration_version().value()
                                        : "";
  const bool vo_enabled_for_tracking = rig.has_value() && estimator_mode == "stereo_landmark_vo";

  int num_snapshot_timestamp_missing = 0;
  for (int i = 0; i < static_cast<int>(problem.KeyframeOrder().size()); ++i) {
    const std::string& kf_id = problem.KeyframeOrder()[i];
    const auto pose = problem.GetKeyframePose(kf_id);

    uw::application::ReplayTrackingInputs tracking_inputs;
    tracking_inputs.solver_converged = summary.converged;
    tracking_inputs.vo_enabled = vo_enabled_for_tracking;
    const auto vo_health_it = vo_health_by_keyframe.find(kf_id);
    if (vo_health_it != vo_health_by_keyframe.end()) tracking_inputs.vo_health = vo_health_it->second;

    uw::application::StateSnapshotInputs snapshot_inputs;
    snapshot_inputs.state_id = kf_id;
    snapshot_inputs.state_version = static_cast<uint64_t>(i) + 1;
    snapshot_inputs.pose = pose;
    const auto capture_time_it = capture_time_by_keyframe.find(kf_id);
    if (capture_time_it != capture_time_by_keyframe.end()) {
      snapshot_inputs.capture_timestamp = capture_time_it->second;
    } else {
      ++num_snapshot_timestamp_missing;  // no camera/GT/evidence time at all: Stamp{} default (epoch)
    }
    snapshot_inputs.calibration_version = calibration_version_for_snapshot;
    const auto evidence_it = evidence_by_keyframe.find(kf_id);
    if (evidence_it != evidence_by_keyframe.end()) snapshot_inputs.contributing_evidence = evidence_it->second;
    snapshot_inputs.tracking_status = uw::application::DecideTrackingStatus(tracking_inputs);

    const auto snapshot = uw::application::BuildStateSnapshot(snapshot_inputs);
    state_store.Commit(snapshot);

    submap_manager.UpdateKeyframePose(kf_id, pose);
    estimated_trajectory.push_back({uw::domain::ToSeconds(snapshot.capture_timestamp()), pose});
  }
  if (num_snapshot_timestamp_missing > 0) {
    std::cout << "warning: " << num_snapshot_timestamp_missing
              << " keyframe(s) had no camera/GT/evidence timestamp at all; capture_timestamp defaults to "
                 "epoch\n";
  }

  // Acoustic-optic pass (only when --experiment loaded a rig with cameras):
  // per keyframe, run StereoOpticalDepthFrontend -> SonarCfarFrontend
  // (reused, same instance as the sonar pass above) ->
  // AcousticOpticDepthFusionFrontend::Fuse -> BuildMapEvidenceFromFusedDepth,
  // depositing a THIRD MapEvidence bucket into submap_manager (keyed per
  // keyframe, alongside the existing "landmarks" bucket) using the pose
  // ALREADY committed above. This never touches PoseGraphProblem/the solver
  // /ATE — dense depth does not become a new factor type.
  int num_keyframes_with_camera = 0;
  int num_acoustic_optic_accepted = 0;
  int num_acoustic_optic_ambiguous = 0;
  int num_acoustic_optic_conflict = 0;
  int num_acoustic_optic_rejected = 0;
  int num_sync_invalid_timestamp = 0;
  int num_map_evidence_points = 0;
  MapContributionCounts total_contributions;
  if (rig.has_value()) {
    // left_by_kf_raw / right_by_kf_raw / get_rectified are defined above,
    // shared with the relative-pose block's stereo_landmark_vo_frontend
    // path.
    std::unordered_map<std::string, uw::domain::SonarFrame> sonar_by_kf;
    for (const auto& f : input.sonar_frames) {
      // v1 top-1 rule (see file header): keep the first sonar frame seen
      // per keyframe if more than one target was in range.
      const std::string kf_id = f.header().observation_id().value();
      if (sonar_by_kf.find(kf_id) == sonar_by_kf.end()) sonar_by_kf[kf_id] = f;
    }

    uw::frontends::StereoOpticalDepthFrontendParams stereo_params;
    stereo_params.left_frame = rectification_context->LeftRectifiedFrame();
    stereo_params.right_frame = rectification_context->RightRectifiedFrame();
    stereo_params.matcher.min_texture_variance = defaults.stereo_matching.min_texture_variance;
    stereo_params.matcher.min_uniqueness_margin = defaults.stereo_matching.min_uniqueness_margin;
    stereo_params.matcher.left_right_max_diff_px = defaults.stereo_matching.left_right_max_diff_px;
    uw::frontends::StereoOpticalDepthFrontend stereo_frontend(stereo_params);
    uw::frontends::AcousticOpticDepthFusionParams fusion_params;
    uw::frontends::AcousticOpticDepthFusionFrontend fusion_frontend(fusion_params);
    uw::mapping::AcousticOpticMapBridgeParams bridge_params;

    for (std::size_t kf_index = 0; kf_index < problem.KeyframeOrder().size(); ++kf_index) {
      const std::string& kf_id = problem.KeyframeOrder()[kf_index];
      auto left_raw_it = left_by_kf_raw.find(kf_id);
      auto right_raw_it = right_by_kf_raw.find(kf_id);
      if (left_raw_it == left_by_kf_raw.end() || right_raw_it == right_by_kf_raw.end()) continue;
      ++num_keyframes_with_camera;

      const auto sonar_it = sonar_by_kf.find(kf_id);
      uw::runtime::SynchronizerParams sync_params;
      // The synchronizer and its downstream time_delta below still consume
      // RAW image headers (capture_time, sensor_frame) -- rectification
      // only changes pixel content/frame naming, not capture timing.
      const auto sync_decision = uw::runtime::SynchronizeAcousticOptic(
          left_raw_it->second, std::optional<uw::domain::ImageFrame>(right_raw_it->second),
          sonar_it != sonar_by_kf.end() ? std::optional<uw::domain::SonarFrame>(sonar_it->second)
                                        : std::nullopt,
          *rig, sync_params);

      auto* rectified = get_rectified(kf_id);
      if (rectified == nullptr) continue;
      const auto optical_evidence =
          stereo_frontend.Process(rectified->images, rectification_context->DerivedRig());
      if (!optical_evidence.has_value()) continue;

      // kSynchronized/kTimeDeltaExceeded both hand the REAL sonar hypothesis
      // and REAL delta to Fuse() -- the associator's own first-checked time
      // gate (frontends/acoustic_optic_associator.cpp) is what turns an
      // excessive delta into a REJECTED/TIME_DELTA record before any
      // geometric projection, so this file no longer needs to (and must
      // not) fake a zero delta to route around that decision. kNoSonar and
      // kInvalidTimestamp both fall through with an empty hypothesis set,
      // which makes Fuse() return a purely optical-only result with no
      // association record at all -- the optical chain never stops running
      // just because the cross-modal pairing did.
      uw::domain::HypothesisSet sonar_hypotheses;
      switch (sync_decision.status) {
        case uw::runtime::SynchronizationStatus::kSynchronized:
        case uw::runtime::SynchronizationStatus::kTimeDeltaExceeded:
          sonar_hypotheses = sonar_frontend.ProcessSonarFrame(sonar_it->second);
          break;
        case uw::runtime::SynchronizationStatus::kNoSonar:
          break;
        case uw::runtime::SynchronizationStatus::kInvalidTimestamp:
          ++num_sync_invalid_timestamp;
          break;
      }

      const auto fused_result =
          fusion_frontend.Fuse(sonar_hypotheses, *optical_evidence, rectification_context->DerivedRig(),
                                sync_decision.max_pairwise_time_delta_s);
      if (!fused_result.has_value()) continue;

      const auto& fused = uw::domain::GetPayload<uw::domain::FusedDepthMeasurement>(fused_result->fused_evidence);
      const auto contribution_counts = CountDepthContributions(fused);
      total_contributions.optical_only_points += contribution_counts.optical_only_points;
      total_contributions.acoustic_optic_points += contribution_counts.acoustic_optic_points;
      if (fused.associations_size() > 0) {
        switch (fused.associations(0).status()) {
          case uw::domain::ACOUSTIC_OPTIC_ASSOCIATION_STATUS_ACCEPTED:
            ++num_acoustic_optic_accepted;
            break;
          case uw::domain::ACOUSTIC_OPTIC_ASSOCIATION_STATUS_AMBIGUOUS:
            ++num_acoustic_optic_ambiguous;
            break;
          case uw::domain::ACOUSTIC_OPTIC_ASSOCIATION_STATUS_CONFLICT:
            ++num_acoustic_optic_conflict;
            break;
          case uw::domain::ACOUSTIC_OPTIC_ASSOCIATION_STATUS_REJECTED:
            ++num_acoustic_optic_rejected;
            break;
          default:
            break;
        }
      }

      const uint64_t state_version = kf_index + 1;
      const auto map_evidence = uw::mapping::BuildMapEvidenceFromFusedDepth(
          fused_result->fused_evidence, rectification_context->DerivedRig(), bridge_params, kf_id,
          state_version);
      if (map_evidence.has_value()) {
        num_map_evidence_points +=
            static_cast<int>(map_evidence->geometry_or_occupancy().size() / (3 * sizeof(float)));
        submap_manager.AddMapEvidence(*map_evidence);
      }
    }
    std::cout << "acoustic-optic: " << num_keyframes_with_camera << " keyframes with camera data, "
              << num_acoustic_optic_accepted << " accepted, " << num_acoustic_optic_ambiguous
              << " ambiguous, " << num_acoustic_optic_conflict << " conflict, " << num_acoustic_optic_rejected
              << " rejected, " << num_sync_invalid_timestamp
              << " sync invalid-timestamp (optical-only), " << num_map_evidence_points
              << " map evidence points added (" << total_contributions.optical_only_points
              << " optical-only, " << total_contributions.acoustic_optic_points << " acoustic-optic)\n";
  }

  const auto ate =
      uw::evaluation::ComputeAte(estimated_trajectory, ground_truth_trajectory, 0.05, opt.align_ate);
  std::cout << "ATE: rmse=" << ate.rmse_m << "m mean=" << ate.mean_m << "m max=" << ate.max_m
            << "m (" << ate.num_matched_poses << " matched poses)\n";

  uw::application::ReplayRunSummary run_summary;
  run_summary.estimator_mode = estimator_mode;
  run_summary.solver = defaults.solver;
  run_summary.solver_converged = summary.converged;
  run_summary.solver_iterations = summary.iterations;
  run_summary.initial_cost = summary.initial_cost;
  run_summary.final_cost = summary.final_cost;
  run_summary.keyframe_count = static_cast<int>(problem.NumKeyframes());
  run_summary.keyframe_boundary_count = static_cast<int>(input.keyframe_boundaries.size());
  run_summary.imu_factor_count = num_imu_factors;
  run_summary.imu_interval_rejected_count = num_imu_intervals_rejected;
  run_summary.relative_pose_factor_count = num_relative_pose_factors;
  run_summary.loop_closure_factor_count = num_loop_closure_factors;
  run_summary.sonar_range_factor_count = num_sonar_factors;
  run_summary.depth_factor_count = num_depth_factors;
  run_summary.landmark_count = num_landmarks_discovered;
  if (imu_mode) {
    run_summary.initialization =
        inertial_initialization->mode ==
                uw::frontends::ImuStationaryInitialization::Mode::kStationary
            ? "stationary"
            : "wide_velocity_prior";
  }
  run_summary.free_parameter_dim = observability.free_parameter_dim;
  run_summary.residual_dim = observability.residual_dim;
  run_summary.ate_rmse_m = ate.rmse_m;
  run_summary.ate_matched_poses = ate.num_matched_poses;
  std::cout << uw::application::FormatReplayRunSummary(run_summary);

  {
    std::ofstream traj_out(opt.out_prefix + "_trajectory.tum");
    for (const auto& pose_entry : estimated_trajectory) {
      traj_out << ToTumLine(pose_entry.timestamp_s, pose_entry.pose_WB) << "\n";
    }
  }

  if (write_run_manifest) {
    uw::runtime::RunManifest manifest;
    manifest.run_id = "replay_demo_" + std::to_string(
                                            std::chrono::duration_cast<std::chrono::seconds>(
                                                std::chrono::system_clock::now().time_since_epoch())
                                                .count());
    manifest.git_commit = git_commit;
    manifest.config_hash = config_hash;
    manifest.calibration_hash = calibration_hash;
    manifest.derived_calibration_hash =
        rectification_context.has_value()
            ? Fnv1aHex(rectification_context->DerivedRig().SerializeAsString())
            : "";
    manifest.dataset_or_scenario = opt.bag_path;
    manifest.simulator = "synthetic (apps/synth_bag_gen.cpp)";
    manifest.os_info = DetectOsInfo();
    manifest.cpu_info = DetectCpuInfo();
    manifest.gpu_info = "n/a (CPU-only Eigen pipeline, no GPU dependency in this build)";
    manifest.seed = scenario_seed;
    manifest.start_time_iso8601 = run_start_time_iso8601;
    manifest.end_time_iso8601 = NowIso8601Utc();
    std::ofstream manifest_out(opt.out_prefix + "_run_manifest.json");
    manifest_out << manifest.ToJson();
    std::cout << "wrote " << opt.out_prefix << "_trajectory.tum and " << opt.out_prefix
              << "_run_manifest.json\n";
  } else {
    std::cout << "wrote " << opt.out_prefix << "_trajectory.tum (run_manifest disabled by config)\n";
  }

  // P0 non-void gates (docs/archive/uw-slam-production-readiness-and-roadmap-2026-
  // 08-21.md section 5.5): outputs above are always written for
  // diagnosability even on failure — only the exit code changes — so a CI
  // gate failure still leaves a trajectory/manifest to inspect. Each gate
  // is individually opt-in via defaults.*/experiment `gates:` (see
  // include/runtime/config.hpp) except require_converged, which defaults on
  // because a stalled solver is never an acceptable output.
  const std::vector<std::string> gate_failures =
      EvaluateReplayGates(defaults, summary, ate, num_landmarks_discovered, total_contributions,
                          num_acoustic_optic_accepted);
  if (!gate_failures.empty()) {
    std::cerr << "GATE FAILURE:\n";
    for (const auto& failure : gate_failures) std::cerr << "  - " << failure << "\n";
    return 2;
  }
  return 0;
}
